create proc GENERAR_CODIGO_CLIENTE
AS
BEGIN
SELECT  TOP 1 IDCLIENTE+1 FROM CLIENTES ORDER BY IDCLIENTE DESC
END
go

CREATE PROC SP_ELIMINAR_CLIENTE
@ID INT
AS
BEGIN
DELETE FROM CLIENTES WHERE IDCLIENTE = @ID
END
GO

CREATE PROC SP_ACTUALIZAR_CLIENTES
@ID INT,
@NOMBRE VARCHAR(100),
@DIRECCION VARCHAR(100),
@TELEFONO VARCHAR (10),
@DNI VARCHAR(10)
AS
BEGIN
UPDATE CLIENTES SET NOMBRE = @NOMBRE, DIRECCION=@DIRECCION,TELEFONO=@TELEFONO,DNI=@DNI WHERE IDCLIENTE=@ID
END
GO





